### ISSUE TITLE
Relax requirements of pandas version

### ISSUE THREAD

**Issue by keisuke-umezawa** [AlpacaDB/backlight#15]
Can we relax the condition?
https://github.com/AlpacaDB/backlight/blob/master/requirements.txt#L1

**Comment by BinrOp** [comment]
This makes it difficult... 
https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#v0-22-0-december-29-2017

**Comment by keisuke-umezawa** [comment]
Oh, I see. But we cannot install backlight on container...

**Comment by BinrOp** [comment]
If we allow versions of pandas > 0.21.0 for this repo, our client code risk being incompatible with backlight.

We should migrate all our codebase to pandas0.22.x before relaxing the constraint.
cf. issues and PRs on libfs, afp regarding pandas upgrade.

**Comment by BinrOp** [comment]
> Oh, I see. But we cannot install backlight on container...

For which container? libfs?

**Comment by keisuke-umezawa** [comment]
https://github.com/AlpacaDB/alpaca-containers/pull/21

**Comment by keisuke-umezawa** [comment]
I will check it can be installed.

**Comment by BinrOp** [comment]
Why do we want to install it in our containers?

**Comment by BinrOp** [comment]
Oh just checking compatibility? :+1:

**Comment by keisuke-umezawa** [comment]
We should avoid using git submodule, I think. Like libalpaca, we should install backlight with pip?

**Comment by BinrOp** [comment]
I agree I don't like too much submodules either.
Mmmh maybe we should discuss briefly together about this? Ping me anytime!
